Taxonomy:
  uri: '#'
  attributes:
    icon: tags
  children:
    Vocabularies:
      uri: /admin/taxonomy/vocabularies
      attributes:
        icon: circle-o

Assets:
  uri: '#'
  attributes:
    icon: file
  children:
    Assets:
      uri: /admin/assets/assets
      attributes:
        icon: circle-o
    Add asset:
      uri: /admin/assets/assets/add
      attributes:
        icon: circle-o

Users:
  uri: '#'
  attributes:
    icon: users
  children:
    Users:
      uri: /admin/users/users
      attributes:
        icon: circle-o
    Roles:
      uri: /admin/users/roles
      attributes:
        icon: circle-o
    Permissions:
      uri: /admin/acl_manager/aros/role_permissions
      attributes:
        icon: circle-o

Settings:
  uri: '#'
  attributes:
    icon: cogs
  children:
    Settings:
      uri: /admin/settings/settings
      attributes:
        icon: circle-o
    Add setting:
      uri: /admin/settings/settings/add
      attributes:
        icon: circle-o
    Caches:
      uri: /admin/settings/caches
      attributes:
        icon: circle-o
